module.exports = { 
    PROVIDER: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    AWS_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    AWS_SECRET_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    AWS_REGION: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    MODEL: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    CONTEXT: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    AVAILABLE: false,
    LIMIT: 200,
    MAX_LIMIT: 300,
    MAX_TOKENS: 5000,
    EDA_APP_URL: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    MCP_URL: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
};