module.exports = {
    CLOUD_INSTANCE: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    TENANT_ID: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    CLIENT_ID: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    REDIRECT_URI: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    POST_LOGOUT_REDIRECT_URI: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    GRAPH_API_ENDPOINT: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    EXPRESS_SESSION_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXX',
};